# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0d37b0f474f6ecf96ee1864e9fe4bb8"
name = "Loyalty"
application_url = "https://vianisa-loyalty-app-368188768745.us-central1.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "refunds/create" ]
  uri = "/webhooks/refunds/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/create" ]
  uri = "/webhooks/customers/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_all_orders,read_price_rules,read_products,write_customers,write_discounts,write_price_rules,write_products"

[auth]
redirect_urls = [ "https://vianisa-loyalty-app-368188768745.us-central1.run.app/auth", "https://vianisa-loyalty-app-368188768745.us-central1.run.app/auth/callback" ]

